package com.globex.model.entity.pm;
// Generated Mar 11, 2017 11:22:32 AM by Hibernate Tools 5.1.0.Alpha1

import lombok.Data;
import lombok.EqualsAndHashCode;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CoverageArea generated by hbm2java
 */
@Data
@EqualsAndHashCode(exclude = {"organization"})
@Entity
@Table(name = "coverage_area")
public class CoverageArea implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "COVERAGE_AREA_ID", unique = true)
	private Integer coverageAreaId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ORGANIZATION_ID")
	private Organization organization;

    @Column(name = "MARINE")
	private boolean marine;

    @Column(name = "PROPERTY")
	private boolean property;

    @Column(name = "HEALTH_AND_BENEFITS")
	private boolean healthAndBenefits;

    @Column(name = "LIABILITIES")
	private boolean liabilities;

    @Column(name = "DIRECTORS_AND_OFFICERS")
	private boolean directorsAndOfficers;

    @Column(name = "AVIATION")
	private boolean aviation;
}
